# Generated by Django 4.2.7 on 2023-12-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='task_pictures/'),
        ),
    ]
