# Generated by Django 4.2.7 on 2023-12-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tasks_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/task_pictures/'),
        ),
    ]
